body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I made sure that there are *no [existing discussions](https://github.com/orgs/RapidClipse/discussions)* which I could contribute my information to."
          required: true
        - label: "I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise."
          required: true
  - type: textarea
    id: description
    validations:
      required: true
